import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        tertiary: "#0f172a",
        "primary-fixed": "#d8e7ff",
        "on-tertiary-fixed": "#071225",
        "on-background": "#0a1020",
        "on-primary-fixed-variant": "#1d4ed8",
        "electric-blue": "#00c8ff",
        "on-tertiary-container": "#c7d2fe",
        "surface-container-low": "#eef4ff",
        "executive-gray": "#64748b",
        "secondary-container": "#006bff",
        "inverse-on-surface": "#f8fbff",
        "surface-tint": "#1f7aff",
        "on-secondary-container": "#ffffff",
        "inverse-primary": "#9fc5ff",
        outline: "#64748b",
        "on-surface-variant": "#334155",
        background: "#f3f7ff",
        "secondary-fixed": "#dbeafe",
        "on-surface": "#0a1020",
        secondary: "#006bff",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#adc6ff",
        "on-secondary-fixed-variant": "#004493",
        "on-primary-container": "#b7d3ff",
        "glass-stroke": "rgba(107, 151, 210, 0.24)",
        "on-tertiary": "#ffffff",
        "status-success": "#10B981",
        "surface-container-highest": "#d7e3f7",
        "on-primary": "#ffffff",
        error: "#dc2626",
        "primary-fixed-dim": "#b9d6ff",
        "surface-container-high": "#e2ebf8",
        "surface-container": "#eaf1fb",
        "surface-dim": "#d7e2f0",
        "on-tertiary-fixed-variant": "#6b3a22",
        "outline-variant": "#bfd0e6",
        surface: "#f8fbff",
        "surface-variant": "#e8f0fb",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#001a41",
        "on-error-container": "#93000a",
        "surface-bright": "#ffffff",
        "status-critical": "#ff3b3b",
        "tertiary-container": "#06142d",
        "tertiary-fixed": "#ffdbcc",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#feb696",
        "inverse-surface": "#06142d",
        "error-container": "#ffdad6",
        primary: "#071225",
        "primary-container": "#06142d",
        "on-primary-fixed": "#06142d",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        unit: "4px",
        gutter: "24px",
        "container-max": "1440px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "data-mono": ["IBM Plex Mono", "monospace"],
        "body-base": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "display-xl": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["21px", { lineHeight: "28px", fontWeight: "650" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0", fontWeight: "700" }],
        "data-mono": ["13px", { lineHeight: "19px", fontWeight: "500" }],
        "body-base": ["15px", { lineHeight: "23px", fontWeight: "400" }],
        "headline-lg": ["26px", { lineHeight: "34px", fontWeight: "650" }],
        "title-md": ["17px", { lineHeight: "24px", fontWeight: "600" }],
        "display-xl": ["34px", { lineHeight: "42px", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
} satisfies Config;
