import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        tertiary: "#000000",
        "primary-fixed": "#d7e3ff",
        "on-tertiary-fixed": "#351000",
        "on-background": "#1b1b1e",
        "on-primary-fixed-variant": "#32476c",
        "electric-blue": "#00F0FF",
        "on-tertiary-container": "#b37559",
        "surface-container-low": "#f5f3f6",
        "executive-gray": "#64748B",
        "secondary-container": "#0070eb",
        "inverse-on-surface": "#f2f0f4",
        "surface-tint": "#4a5f85",
        "on-secondary-container": "#fefcff",
        "inverse-primary": "#b2c7f3",
        outline: "#74777f",
        "on-surface-variant": "#44474e",
        background: "#faf9fc",
        "secondary-fixed": "#d8e2ff",
        "on-surface": "#1b1b1e",
        secondary: "#0058bc",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#adc6ff",
        "on-secondary-fixed-variant": "#004493",
        "on-primary-container": "#6f84ad",
        "glass-stroke": "rgba(255, 255, 255, 0.4)",
        "on-tertiary": "#ffffff",
        "status-success": "#10B981",
        "surface-container-highest": "#e3e2e5",
        "on-primary": "#ffffff",
        error: "#ba1a1a",
        "primary-fixed-dim": "#b2c7f3",
        "surface-container-high": "#e9e7eb",
        "surface-container": "#efedf1",
        "surface-dim": "#dbd9dd",
        "on-tertiary-fixed-variant": "#6b3a22",
        "outline-variant": "#c4c6cf",
        surface: "#faf9fc",
        "surface-variant": "#e3e2e5",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#001a41",
        "on-error-container": "#93000a",
        "surface-bright": "#faf9fc",
        "status-critical": "#EF4444",
        "tertiary-container": "#011b3e",
        "tertiary-fixed": "#ffdbcc",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#feb696",
        "inverse-surface": "#303033",
        "error-container": "#ffdad6",
        primary: "#000000",
        "primary-container": "#011b3e",
        "on-primary-fixed": "#011b3e",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        unit: "4px",
        gutter: "24px",
        "container-max": "1440px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "data-mono": ["JetBrains Mono", "monospace"],
        "body-base": ["Inter", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "title-md": ["Hanken Grotesk", "sans-serif"],
        "display-xl": ["Hanken Grotesk", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" }],
        "data-mono": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "body-base": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "display-xl": ["48px", { lineHeight: "56px", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
} satisfies Config;
