import PDFDocument from "pdfkit";
import pptxgen from "pptxgenjs";
import { ReportSummary } from "./report-summary.service.js";
import { PassThrough } from "stream";

export const exportService = {
  async generatePDF(summary: ReportSummary): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 50 });
      const chunks: Buffer[] = [];

      doc.on("data", (chunk) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      // Title Page
      doc.fontSize(24).text(summary.title, { align: "center" });
      doc.moveDown();
      doc.fontSize(14).text(`Period: ${summary.period}`, { align: "center" });
      doc.text(`Company ID: ${summary.companyId}`, { align: "center" });
      doc.moveDown(2);

      // Summary Section
      doc.fontSize(18).text("Executive Summary", { underline: true });
      doc.moveDown();
      doc.fontSize(12).text(summary.summary);
      doc.moveDown(2);

      // KPI Section
      doc.fontSize(18).text("Key Performance Indicators", { underline: true });
      doc.moveDown();
      summary.kpis.forEach(kpi => {
        doc.fontSize(12).text(`${kpi.label}: ${kpi.value}`);
      });
      doc.moveDown(2);

      // Insights Section
      doc.fontSize(18).text("Strategic Insights", { underline: true });
      doc.moveDown();
      summary.insights.forEach(insight => {
        doc.fontSize(12).text(`• ${insight}`);
      });
      doc.moveDown(2);

      // Conclusion
      doc.fontSize(18).text("Conclusion", { underline: true });
      doc.moveDown();
      doc.fontSize(12).text("This report was automatically generated by RJT NEXUS360 by RJT Consultoria based on validated operational data.");

      doc.end();
    });
  },

  async generatePPT(summary: ReportSummary): Promise<Buffer> {
    const pres = new pptxgen();

    // 1. Title Slide
    let slide1 = pres.addSlide();
    slide1.addText(summary.title, { x: 1, y: 2, w: "80%", fontSize: 36, bold: true, align: "center", color: "363636" });
    slide1.addText(`Period: ${summary.period}`, { x: 1, y: 3, w: "80%", fontSize: 18, align: "center", color: "666666" });

    // 2. Executive Summary
    let slide2 = pres.addSlide();
    slide2.addText("Executive Summary", { x: 0.5, y: 0.5, w: "90%", fontSize: 24, bold: true, color: "0088CC" });
    slide2.addText(summary.summary, { x: 0.5, y: 1.5, w: "90%", fontSize: 14, color: "333333" });

    // 3. KPI Slide
    let slide3 = pres.addSlide();
    slide3.addText("Key Performance Indicators", { x: 0.5, y: 0.5, w: "90%", fontSize: 24, bold: true, color: "0088CC" });
    const kpiRows = summary.kpis.map(kpi => [
      { text: kpi.label, options: { bold: true } },
      { text: kpi.value.toString() }
    ]);
    slide3.addTable(kpiRows, { x: 0.5, y: 1.5, w: 9, border: { type: "solid", color: "E1E1E1" } });

    // 4. Insight Slide
    let slide4 = pres.addSlide();
    slide4.addText("Strategic Insights", { x: 0.5, y: 0.5, w: "90%", fontSize: 24, bold: true, color: "0088CC" });
    slide4.addText(summary.insights.map(i => `• ${i}`).join("\n"), { x: 0.5, y: 1.5, w: "90%", fontSize: 14, color: "333333" });

    // 5. Conclusion Slide
    let slide5 = pres.addSlide();
    slide5.addText("Conclusion", { x: 0.5, y: 0.5, w: "90%", fontSize: 24, bold: true, color: "0088CC" });
    slide5.addText("This report was automatically generated by RJT NEXUS360 by RJT Consultoria based on validated operational data.", { x: 0.5, y: 1.5, w: "90%", fontSize: 14, color: "333333" });

    const buffer = await pres.write({ outputType: "nodebuffer" }) as Buffer;
    return buffer;
  }
};
